package cotesmodulos;


/**
* cotesmodulos/cotesinterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cotesfacturas.idl
* miércoles 26 de junio de 2019 05:43:21 PM BOT
*/

public interface cotesinterfaceOperations 
{
  String facturaspendientes (int numero);
  void pagar (int idfactura);
} // interface cotesinterfaceOperations
